import nodemailer from 'nodemailer';
import { logger } from '../utils/logger.js';

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
  text?: string;
}

// Create transporter
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

// Verify connection on startup
transporter.verify((error) => {
  if (error) {
    logger.error('Email service connection error:', error);
  } else {
    logger.info('✅ Email service is ready');
  }
});

export async function sendEmail(options: EmailOptions): Promise<void> {
  try {
    const mailOptions = {
      from: process.env.SMTP_FROM || 'noreply@pmapp.com',
      to: options.to,
      subject: options.subject,
      html: options.html,
      text: options.text || options.html.replace(/<[^>]*>/g, ''), // Strip HTML for text version
    };

    await transporter.sendMail(mailOptions);
    logger.info(`Email sent to ${options.to}: ${options.subject}`);
  } catch (error) {
    logger.error('Failed to send email:', error);
    throw error;
  }
}

export async function sendWelcomeEmail(userEmail: string, userName: string): Promise<void> {
  await sendEmail({
    to: userEmail,
    subject: 'Welcome to Project Management App',
    html: `
      <h1>Welcome ${userName}!</h1>
      <p>Thank you for joining our project management platform.</p>
      <p>Get started by creating your first project.</p>
      <p><a href="${process.env.FRONTEND_URL}/dashboard">Go to Dashboard</a></p>
    `,
  });
}

export async function sendProjectInvitation(
  userEmail: string,
  projectName: string,
  inviterName: string
): Promise<void> {
  await sendEmail({
    to: userEmail,
    subject: `You've been invited to ${projectName}`,
    html: `
      <h2>Project Invitation</h2>
      <p>${inviterName} has invited you to join the project <strong>${projectName}</strong>.</p>
      <p><a href="${process.env.FRONTEND_URL}/projects">View Project</a></p>
    `,
  });
}

export async function sendWeeklyReport(
  userEmail: string,
  reportData: {
    totalProjects: number;
    completedTasks: number;
    upcomingDeadlines: number;
    budgetAlerts: number;
  }
): Promise<void> {
  await sendEmail({
    to: userEmail,
    subject: 'Weekly Project Summary',
    html: `
      <h1>Weekly Project Summary</h1>
      <h2>Your Projects at a Glance</h2>
      <ul>
        <li><strong>Active Projects:</strong> ${reportData.totalProjects}</li>
        <li><strong>Completed Tasks This Week:</strong> ${reportData.completedTasks}</li>
        <li><strong>Upcoming Deadlines:</strong> ${reportData.upcomingDeadlines}</li>
        <li><strong>Budget Alerts:</strong> ${reportData.budgetAlerts}</li>
      </ul>
      <p><a href="${process.env.FRONTEND_URL}/dashboard">View Full Dashboard</a></p>
      <hr/>
      <p style="color: #666; font-size: 12px;">Generated by Project Management App</p>
    `,
  });
}
